//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaturaOtomasyon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teklif
    {
        public int Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Indirim { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public Nullable<bool> Odendi { get; set; }
        public Nullable<System.DateTime> BasTarih { get; set; }
        public Nullable<System.DateTime> GecerlilikTarih { get; set; }
        public string Bilgilendirme { get; set; }
        public Nullable<int> TeklifDurum { get; set; }
        public string UrunBaslik { get; set; }
        public Nullable<decimal> UrunFiyat { get; set; }
        public string Note { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual TeklifDurum TeklifDurum1 { get; set; }
    }
}
